fragment QuoteFragment on ComponentTextQuote {
  id
  Quote
  Author
}

fragment TextContentFragment on ComponentTextTitleContentContent {
  id
  Title
  center_content
  main_content
}

fragment ImagesContentFragment on ComponentImagesImages {
  id
  images {
    data {
      ...UploadFileAttributesFragment
    }
  }
}

fragment ClassListFragment on ComponentListClassLevelList {
  id 
  title 
  before_list
  list {
    data {
      id
      attributes {
        title
        description
      }
    }
  }
}

fragment TeacherListFragment on ComponentListTeachersList {
  id 
  title 
  before_list
  list {
    data {
      id
      attributes {
        title
        description
        image {
          data {
            ...UploadFileAttributesFragment
          }
        }
      }
    }
  }
}

fragment RetreatListFragment on ComponentListRetreatsList {
  id 
  title 
  before_list
  list {
    data {
      id
      attributes {
        title: location
        images {
          data {
            ...UploadFileAttributesFragment
          }
        }
      }
    }
  }
}

fragment UploadFileAttributesFragment on UploadFileEntity {
  attributes {
    width
    height
    formats
    ext
    size
    url 
  }
}

query GetPage($id: ID) {
  page(id: $id) {
    data {
      id
      attributes {
        banner_image {
          data {
            ...UploadFileAttributesFragment
          }
        }
        content {
          ...QuoteFragment
          ...TextContentFragment
          ...ImagesContentFragment
          ...ClassListFragment
          ...TeacherListFragment
          ...RetreatListFragment
        }
      }
    }
  }
}